apiVersion: v1
kind: Service
metadata:
  name: conduktor-console
spec:
  type: LoadBalancer
  selector:
    app: conduktor-console
  ports:
    - name: console-port
      port: 8080
      targetPort: 8080
