apiVersion: v1
kind: Service
metadata:
  name: conduktor-monitoring
spec:
  type: ClusterIP
  selector:
    app: conduktor-monitoring
  ports:
  - name: cortex-api
    port: 9009
    targetPort: 9009
  - name: am-api
    port: 9010
    targetPort: 9010
  - name: prom-api
    port: 9090
    targetPort: 9090
