apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: '{{ .Values.postgresql.image }}'
        ports:
        - containerPort: 5432
          name: postgres-port
        env:
        - name: POSTGRES_DB
          value: '{{ .Values.postgresql.db }}'
        - name: POSTGRES_USER
          value: '{{ .Values.postgresql.user }}'
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: postgresql-password
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}
