apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
type: Opaque
stringData:
  postgresql-password: password
  conduktor-admin-email: admin@example.com
  conduktor-admin-password: admin_password
  cdk-database-url: postgresql://conduktor:password@postgres:5432/conduktor-console
