apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
  - name: client-port
    port: {{ .Values.zookeeper.clientPort }}
    targetPort: {{ .Values.zookeeper.clientPort }}
