version: '3.8'

services:
  kafka-1:
    image: bitnami/kafka:3.9.0
    container_name: kafka-1
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=QGu1053dSe-cQk7XcwtEAA
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9095,3@kafka-3:9097
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - '9092:9092'
      - '9093:9093'
    networks:
      - kafka-net
    restart: on-failure

  kafka-2:
    image: bitnami/kafka:3.9.0
    container_name: kafka-2
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=QGu1053dSe-cQk7XcwtEAA
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9095,3@kafka-3:9097
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - '9094:9094'
      - '9095:9095'
    networks:
      - kafka-net
    restart: on-failure

  kafka-3:
    image: bitnami/kafka:3.9.0
    container_name: kafka-3
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=QGu1053dSe-cQk7XcwtEAA
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9096,CONTROLLER://:9097
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9095,3@kafka-3:9097
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - '9096:9096'
      - '9097:9097'
    networks:
      - kafka-net
    restart: on-failure

  postgresql:
    image: postgres:14
    hostname: postgresql
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "conduktor-console"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "password"
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conduktor"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure

  conduktor-console:
    image: conduktor/conduktor-console:1.28.0
    depends_on:
      postgresql:
        condition: service_healthy
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started
      kafka-3:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - conduktor_data:/var/conduktor
    environment:
      CDK_DATABASE_URL: "postgresql://conduktor:password@postgresql:5432/conduktor-console"
      CDK_ORGANIZATION_NAME: "kafka-cluster"
      CDK_ADMIN_EMAIL: "admin@example.com"
      CDK_ADMIN_PASSWORD: "admin_password"
      CDK_CLUSTERS_0_ID: "local-kafka"
      CDK_CLUSTERS_0_NAME: "Local Kafka Cluster"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-1:9092,kafka-2:9094,kafka-3:9096"
      CDK_CLUSTERS_0_COLOR: "#6A57C8"
      CDK_CLUSTERS_0_ICON: "kafka"
      CDK_MONITORING_CORTEX-URL: "http://conduktor-monitoring:9009/"
      CDK_MONITORING_ALERT-MANAGER-URL: "http://conduktor-monitoring:9010/"
      CDK_MONITORING_CALLBACK-URL: "http://conduktor-console:8080/monitoring/api/"
      CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: "http://localhost:8080"
      CDK_LOG_TIMEZONE: "Europe/Berlin"
    networks:
      - kafka-net
    restart: on-failure

  conduktor-monitoring:
    image: conduktor/conduktor-console-cortex:1.28.0
    environment:
      CDK_CONSOLE-URL: "http://conduktor-console:8080"
      CDK_LOG_TIMEZONE: "Europe/Berlin"
    networks:
      - kafka-net
    ports:
      - "9009:9009"
      - "9010:9010"
      - "9090:9090"
    volumes:
      - conduktor_monitoring_data:/var/conduktor/monitoring
    restart: on-failure

  conduktor-gateway:
    image: conduktor/conduktor-gateway:3.0.5
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9094,kafka-3:9096"
      GATEWAY_ADVERTISED_HOST: "localhost"
      GATEWAY_PORT_START: 9099
      GATEWAY_PORT_COUNT: 3
    ports:
      - "9099-9101:9099-9101"
    networks:
      - kafka-net
    restart: on-failure

  kafka-cli:
    image: bitnami/kafka:3.9.0
    container_name: kafka-cli
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    entrypoint: /bin/sh -c "while true; do sleep 1000; done"
    init: true
    networks:
      - kafka-net
    restart: unless-stopped
    tty: true

networks:
  kafka-net:

volumes:
  pg_data: {}
  conduktor_data: {}
  conduktor_monitoring_data:
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
